mon_icinga_mysql_password: "{{ vault_mon_icinga_mysql_password }}"
mon_icinga_mysql_director_password: "{{ vault_mon_icinga_mysql_director_password }}"
mon_icinga_mysql_web_password: "{{ vault_mon_icinga_mysql_web_password }}"
mon_icinga_director_password: "{{ vault_mon_icinga_director_password }}"
grafana_mariadb_password: "{{ vault_grafana_mariadb_password }}"

grafana_enable_keycloak: False
grafana_enable_ansible_db: True
grafana_session_provider: mysql
grafana_session_provider_options: "grafana:{{ grafana_mariadb_password }}@tcp(127.0.0.1:3306)/grafana"
grafana_analytics: False

apt_with_backports: True
