---
  # Slap base SOS-ETH-style debian config onto all hosts
  - hosts: base
    gather_facts: True
    roles:
      - name: apt
        tags: apt
      - name: regional
        tags: regional
      - name: time
        tags: time
        #      - name: apt-dater-host
        #        tags: apt
      - name: motd
        tags: motd
      - name: network
        tags: network
      - name: programs
        tags: programs
      - name: sh
        tags: sh
      - name: ssh
        tags: ssh
      - name: tmux
        tags: tmux
      - name: zsh
        tags: zsh

  # Setup DHCP server with failover
  - hosts: dhcp
    gather_facts: True
    roles:
      - name: dhcp
        tags: dhcp

  # Setup MariaDB Galera Cluster + Radius
  - hosts: radius
    roles:
      - role: local-ca
        tags: local-ca
        local_ca_caname: galera
        local_ca_client:
          pem:
            cert: /etc/haproxy/mdb-cl.crt
            key: /etc/haproxy/mdb-cl.key
          cn: "{{ ansible_nodename }}-client"
        local_ca_ca:
          cert: /etc/haproxy/mdb-ca.crt
          crl: "/etc/haproxy/mdb-crl.pem"
        local_ca_server:
          pem:
            cert: /etc/haproxy/mdb-sv.crt
            key: /etc/haproxy/mdb-sv.key
          cn: "{{ ansible_nodename }}-server"
      - role: local-ca
        tags: local-ca
        local_ca_caname: radius
        local_ca_owner: freerad
        local_ca_ca:
          cert: /etc/freeradius/3.0/certs/ca.pem
        local_ca_server:
          pem:
            cert: /etc/freeradius/3.0/certs/server.pem
            key: /etc/freeradius/3.0/certs/server.key
          cn: "{{ ansible_nodename }}-server"
          san: "DNS:{{ ansible_nodename }},DNS:{{ ansible_fqdn }},IP:{{ansible_all_ipv4_addresses|join(',IP:')}},IP:127.0.0.1"
      - name: haproxy
        tags: haproxy
      - name: mariadb-ha
        tags:
          - mariadb
          - mariadb-ha
      - name: radius
        tags:
          - radius
      - name: kea
        tags:
          - kea
