mon_enable_prometheus_snmp: True

# Demo for Icinga snmp check
mon_check_snmp_hosts:
  - name: "Switch Uptime"
    ip: 10.233.254.253
    oid: "1.3.6.1.2.1.1.3.0"

mon_snmp_map:
  monitoring.lan.geco.ethz.ch:
    - name: row1-switch1
      ip: 10.233.254.25
      interval: '30s'
    - name: row1-switch2
      ip: 10.233.254.3
      interval: '30s'
    - name: row2-switch1
      ip: 10.233.254.6
      interval: '30s'
    - name: row2-switch2
      ip: 10.233.254.8
      interval: '30s'
    - name: row3-switch1
      ip: 10.233.254.10
      interval: '30s'
    - name: row3-switch2
      ip: 10.233.254.7
      interval: '30s'
    - name: row4-switch1
      ip: 10.233.254.5
      interval: '30s'
    - name: row4-switch2
      ip: 10.233.254.30
      interval: '30s'
    - name: server
      ip: 10.233.254.253
      interval: '30s'
