kea_mysql_database: 'radius'
kea_mysql_user: 'radius'
kea_mysql_password: '{{ vault_mariadb_ha_radius_password }}'
kea_mysql_host: 127.44.0.1
kea_mysql_port: 4307

kea_ha_group: 'dhcp_kea'

kea_options:
  - name: domain-name-servers
    data: "10.233.200.1, 10.233.200.2"

kea_pools:
  # Servers
  - subnet: 10.233.253.0/24
    pools:
      - pool: "10.233.253.142 - 10.233.253.145"
    option-data:
      - name: routers
        data: "10.233.253.1"
  # Captive portal
  - subnet: 10.233.240.0/21
    pools:
      - pool: "10.233.240.20 - 10.233.247.253"
    option-data:
      - name: routers
        data: "10.233.240.1"
    relay:
      ip-addresses:
        - 10.233.254.253
  # User switches
  - subnet: 10.233.1.0/24
    pools:
    - pool: "10.233.1.10 - 10.233.1.200"
    option-data:
      - name: routers
        data: "10.233.1.1"
    relay:
      ip-addresses:
        - 10.233.1.1
  - subnet: 10.233.2.0/24
    pools:
    - pool: "10.233.2.10 - 10.233.2.200"
    option-data:
      - name: routers
        data: "10.233.2.1"
    relay:
      ip-addresses:
        - 10.233.2.1
  - subnet: 10.233.3.0/24
    pools:
    - pool: "10.233.3.10 - 10.233.3.200"
    option-data:
      - name: routers
        data: "10.233.3.1"
    relay:
      ip-addresses:
        - 10.233.3.1
  - subnet: 10.233.4.0/24
    pools:
    - pool: "10.233.4.10 - 10.233.4.200"
    option-data:
      - name: routers
        data: "10.233.4.1"
    relay:
      ip-addresses:
        - 10.233.4.1
  - subnet: 10.233.5.0/24
    pools:
    - pool: "10.233.5.10 - 10.233.5.200"
    option-data:
      - name: routers
        data: "10.233.5.1"
    relay:
      ip-addresses:
        - 10.233.5.1
  - subnet: 10.233.6.0/24
    pools:
    - pool: "10.233.6.10 - 10.233.6.200"
    option-data:
      - name: routers
        data: "10.233.6.1"
    relay:
      ip-addresses:
        - 10.233.6.1
  - subnet: 10.233.7.0/24
    pools:
    - pool: "10.233.7.10 - 10.233.7.200"
    option-data:
      - name: routers
        data: "10.233.7.1"
    relay:
      ip-addresses:
        - 10.233.7.1
  - subnet: 10.233.8.0/24
    pools:
    - pool: "10.233.8.10 - 10.233.8.200"
    option-data:
      - name: routers
        data: "10.233.8.1"
    relay:
      ip-addresses:
        - 10.233.8.1
  - subnet: 10.233.9.0/24
    pools:
    - pool: "10.233.9.10 - 10.233.9.200"
    option-data:
      - name: routers
        data: "10.233.9.1"
    relay:
      ip-addresses:
        - 10.233.9.1
  - subnet: 10.233.10.0/24
    pools:
    - pool: "10.233.10.10 - 10.233.10.200"
    option-data:
      - name: routers
        data: "10.233.10.1"
    relay:
      ip-addresses:
        - 10.233.10.1
  - subnet: 10.233.11.0/24
    pools:
    - pool: "10.233.11.10 - 10.233.11.200"
    option-data:
      - name: routers
        data: "10.233.11.1"
    relay:
      ip-addresses:
        - 10.233.11.1
  - subnet: 10.233.12.0/24
    pools:
    - pool: "10.233.12.10 - 10.233.12.200"
    option-data:
      - name: routers
        data: "10.233.12.1"
    relay:
      ip-addresses:
        - 10.233.12.1
  - subnet: 10.233.13.0/24
    pools:
    - pool: "10.233.13.10 - 10.233.13.200"
    option-data:
      - name: routers
        data: "10.233.13.1"
    relay:
      ip-addresses:
        - 10.233.13.1
  - subnet: 10.233.14.0/24
    pools:
    - pool: "10.233.14.10 - 10.233.14.200"
    option-data:
      - name: routers
        data: "10.233.14.1"
    relay:
      ip-addresses:
        - 10.233.14.1
  - subnet: 10.233.15.0/24
    pools:
    - pool: "10.233.15.10 - 10.233.15.200"
    option-data:
      - name: routers
        data: "10.233.15.1"
    relay:
      ip-addresses:
        - 10.233.15.1
  - subnet: 10.233.16.0/24
    pools:
    - pool: "10.233.16.10 - 10.233.16.200"
    option-data:
      - name: routers
        data: "10.233.16.1"
    relay:
      ip-addresses:
        - 10.233.16.1
  - subnet: 10.233.17.0/24
    pools:
    - pool: "10.233.17.10 - 10.233.17.200"
    option-data:
      - name: routers
        data: "10.233.17.1"
    relay:
      ip-addresses:
        - 10.233.17.1
  - subnet: 10.233.18.0/24
    pools:
    - pool: "10.233.18.10 - 10.233.18.200"
    option-data:
      - name: routers
        data: "10.233.18.1"
    relay:
      ip-addresses:
        - 10.233.18.1
  - subnet: 10.233.19.0/24
    pools:
    - pool: "10.233.19.10 - 10.233.19.200"
    option-data:
      - name: routers
        data: "10.233.19.1"
    relay:
      ip-addresses:
        - 10.233.19.1
  - subnet: 10.233.20.0/24
    pools:
    - pool: "10.233.20.10 - 10.233.20.200"
    option-data:
      - name: routers
        data: "10.233.20.1"
    relay:
      ip-addresses:
        - 10.233.20.1
  - subnet: 10.233.21.0/24
    pools:
    - pool: "10.233.21.10 - 10.233.21.200"
    option-data:
      - name: routers
        data: "10.233.21.1"
    relay:
      ip-addresses:
        - 10.233.21.1
  - subnet: 10.233.22.0/24
    pools:
    - pool: "10.233.22.10 - 10.233.22.200"
    option-data:
      - name: routers
        data: "10.233.22.1"
    relay:
      ip-addresses:
        - 10.233.22.1
  - subnet: 10.233.23.0/24
    pools:
    - pool: "10.233.23.10 - 10.233.23.200"
    option-data:
      - name: routers
        data: "10.233.23.1"
    relay:
      ip-addresses:
        - 10.233.23.1
  - subnet: 10.233.24.0/24
    pools:
    - pool: "10.233.24.10 - 10.233.24.200"
    option-data:
      - name: routers
        data: "10.233.24.1"
    relay:
      ip-addresses:
        - 10.233.24.1
  - subnet: 10.233.25.0/24
    pools:
    - pool: "10.233.25.10 - 10.233.25.200"
    option-data:
      - name: routers
        data: "10.233.25.1"
    relay:
      ip-addresses:
        - 10.233.25.1
  # Streaming
  - subnet: 10.233.30.0/24
    pools:
    - pool: "10.233.30.10 - 10.233.30.200"
    option-data:
      - name: routers
        data: "10.233.30.1"
    relay:
      ip-addresses:
        - 10.233.30.1
  # Admin
  - subnet: 10.233.31.0/24
    pools:
    - pool: "10.233.31.10 - 10.233.31.200"
    option-data:
      - name: routers
        data: "10.233.31.1"
    relay:
      ip-addresses:
        - 10.233.31.1
