mon_icinga_mysql_password: "GFUdLDi7CFSYH2eGT3+KTBDPjx4QMyGedqcjByVm^d29cP7t"
mon_icinga_mysql_director_password: "GFUdLDi7CFSYH2eGT3+KTBDPjx4QMyGedqcjByVm^d29cP7t"
mon_icinga_mysql_web_password: "GFUdLDi7CFSYH2eGT3+KTBDPjx4QMyGedqcjByVm^d29cP7t"
mon_icinga_director_password: "GFUdLDi7CFSYH2eGT3+KTBDPjx4QMyGedqcjByVm^d29cP7t"

