mon_syslog_servers:
  - monitoring.lan.geco.ethz.ch

mon_icinga_base_url: "https://monitoring.lan.geco.ethz.ch"
mon_icinga_master_fqdn: monitoring.lan.geco.ethz.ch
mon_icinga_mail_domain: geco.ethz.ch
mon_enable_syslog_forwarding: False

mon_prometheus_job_relabling:
  - source_labels: [job]
    regex: '(.*)_lan_geco_ethz_ch$'
    replacement: '$1.lan_geco.ethz.ch'
    target_label: job
  - source_labels: [job]
    regex: '(.*)_geco_ethz_ch$'
    replacement: '$1.geco.ethz.ch'
    target_label: job
  - source_labels: [job]
    regex: '(.*)_ethz_ch$'
    replacement: '$1.ethz.ch'
    target_label: job
  - source_labels: [job]
    regex: '(.*)_ch$'
    replacement: '$1.ch'
    target_label: job
  - source_labels: [target]
    regex: '(.*)_lan_geco_ethz_ch$'
    replacement: '$1.lan_geco.ethz.ch'
    target_label: target
  - source_labels: [target]
    regex: '(.*)_geco_ethz_ch$'
    replacement: '$1.geco.ethz.ch'
    target_label: target
  - source_labels: [target]
    regex: '(.*)_ethz_ch$'
    replacement: '$1.ethz.ch'
    target_label: target
  - source_labels: [target]
    regex: '(.*)_ch$'
    replacement: '$1.ch'
    target_label: target
  - source_labels: [__name__]
    regex: 'go_.*'
    action: drop
  - source_labels: [__name__]
    regex: 'prometheus_.*'
    action: drop
  - source_labels: [__name__]
    regex: 'http_.*'
    action: drop

mon_icinga_listen_port: 5665
mon_ups_check_temp: False
