---
galaxy_info:
  description: Configure OpenSSH's server and client
  issue_tracker_url: https://github.com/SOSETH/ssh/issues
  license: GPLv3
  min_ansible_version: 2.6
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
       - trusty
       - xenial
       - bionic
    - name: Fedora
      versions:
        - 25
  galaxy_tags:
    - system
    - security
    - ssh
    - kerberos
